### ISSUE TITLE
Pictures not loading on mobile or computer

### ISSUE THREAD

**Issue by gg5150** [josephrocca/OpenCharacters#25]
I used the code to make my characters show ‘facial expressions’ or pictures but instead of showing the picture it just shows a black square with a blue question mark on my phone, and just the text for the emotion on my computer. I can’t ever see the picture. Would anyone happen to know what is going on here?

**Comment by josephrocca** [comment]
@gg5150 Did you upload your images to https://imgur.com/upload? And then wait for the image to fully upload, and right-click on it and copy the URL. The URL that you copy should start with `https://` and end with `.jpg` or `.png` etc.

I'd recommend against using anything other than imgur

**Comment by josephrocca** [comment]
@gg5150 If you are already using Imgur, then, question: Are you using josephrocca.github.io/OpenCharacters or running your own local webserver? If you're using a local web server, you need to use `localhost` in the URL rather than `127.0.0.1` to get imgur images to load properly, as explained [here](https://github.com/josephrocca/OpenCharacters/blob/main/docs/local-setup.md) - weird bug with Imgur's referrer header handling.

**Comment by josephrocca** [comment]
Closed due to no respose
