### ISSUE TITLE
Trouble summarizing text 

### ISSUE THREAD

**Issue by Sam-damn** [josephrocca/OpenCharacters#38]
I noticed that the web app seems to take longer and longer to summarize with every new prompt that i make,i figure this is normal but then at the last prompt it gives me this error message which i included in the image,
![OpenCharacters-bug](https://user-images.githubusercontent.com/77106608/233083815-01039ee1-e864-462b-9bc6-87f860e628e6.jpg)

**Comment by josephrocca** [comment]
You you able to export this thread (the save/floppy-disk icon next to thread card/name) and share it with me? Either here or on discord (username: rocca#4242). If so that would be super helpful for debugging this.

**Comment by Sam-damn** [comment]
Definitely here you go here is the link to the file export of the thread

https://drive.google.com/file/d/1GtL7uAWa0ghpaM3Vnx8cs3f8V-NiLEbD/view?usp=share_link

**Comment by josephrocca** [comment]
Thanks!! This should be fixed now - the previous summarization prompt was sometimes not compressing the text at all. I've now added a thing where if it fails to compress twice in a row, the prompt becomes much more explicit in its instruction to reduce the size of the text (this isn't enabled for the first two attempts because otherwise the model often compresses the text way too much). Please ping me if it's still not working for you

**Comment by Sam-damn** [comment]
It worked now thanks 👍
