### ISSUE TITLE
openAiApiKey suggestion

### ISSUE THREAD

**Issue by jonathanchourio** [josephrocca/OpenCharacters#4]
**_i was trying to set by default the_**   ( let openAiApiKeyOriginal = (await db.misc.get("openAiApiKey"))?.value || "sk---------"; )

**_but then can not hide the apikey... and every time force the label promp:_**

let result = await prompt2({
            openAiApiKey: { label: "Please create a new OpenAI API key and paste it here. Go to <a href='https://platform.openai.com/account/api-keys' target='_blank'>this page</a> to do that. You can change or delete this later by clicking the 'settings' button.", type:"textLine" },
          });

**_im trying to hide the default api key_**
 openAiApiKey: {label: "OpenAI API key:", type: "textLine", placeholder: "(optional)",defaultValue: openAiApiKeyOriginal, **readOnly: true, hidden: true** },

but not works
....woulbe interesting when you set the default apikey value do not force que promp.

its only an suggestion.! Great job! :D

**Comment by josephrocca** [comment]
I'm not 100% sure whether I understand you properly, but let me take a couple of guesses: 

1. You'd like to hide the API key so it shows asterisks
2. Have you downloaded the index.html and utils.js, and are trying to run it in your browser, instead of using the github link (https://josephrocca.github.io/OpenCharacters)? If so, that's definitely something that I want to support. The only problem here, is that (IIUC), `file://` URLs don't have their own persistent storage. So once you refresh the page, you'll lose all your data (and thus need to enter your API key again). Not 100% sure how to solve this, but it may become easy when this feature reaches browsers: https://developer.chrome.com/docs/web-platform/web-bundles/ - web bundles are basically "safe exe files for the web" - i.e. bundle a website up into a simple executable file
